[build]
  command = "node set-env.js && npm run build"
  publish = "dist/PortfolioDanielC/browser"

[[redirects]]
  from = "/gsheets"
  to = ":APPS_SCRIPT_URL"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
